before_script:
  - curl -s https://common-lisp.net/project/cmucl/downloads/snapshots/2016/09/cmucl-2016-09-x86-linux.tar.bz2 | tar xjf -
  - curl -s https://common-lisp.net/project/cmucl/downloads/snapshots/2016/09/cmucl-2016-09-x86-linux.extra.tar.bz2 | tar xjf -

test:
  script:
    - ls
