before_script:
  - wget -nv https://common-lisp.net/project/cmucl/downloads/snapshots/2016/09/cmucl-2016-09-x86-linux.tar.bz2
  - tar xjf cmucl-2016-09-x86-linux.tar.bz2
  - wget -nv https://common-lisp.net/project/cmucl/downloads/snapshots/2016/09/cmucl-2016-09-x86-linux.extra.tar.bz2
  - tar xjf cmucl-2016-09-x86-linux.extra.tar.bz2

test:
  script:
    - ls
